services:
  db:
    image: postgres:15
    container_name: saasescola_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '127.0.0.1:5433:5432'
    volumes:
      - pgdata_escola:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      escola_network:

  saasescola:
    image: kaiquedfelipe08/saasescola
    container_name: saasescola
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      escola_network:

volumes:
  pgdata_escola:

networks:
  escola_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
