version: '3.8'

services:
  db:
    image: postgres:15
    container_name: saasescola_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-saasescola}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - compose-bridge

  saasescola:
    image: kaiquedfelipe08/saasescola
    container_name: saasescola
    environment:
      DATABASE_URL: 'DATABASE_URL=postgresql://postgres.glrbtitaviirszazohhu:${DB_PASSWORD}@aws-0-sa-east-1.pooler.supabase.com:6543/${DB_NAME}'
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - compose-bridge

volumes:
  postgres_data:

networks:
  compose-bridge:
    driver: bridge
