name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup Docker Build
        uses: docker/setup-buildx-action@v3.10.0

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: apisaasescola

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Sanitize branch name
        id: sanitize
        run: |
          SANITIZED=$(echo "${{ github.ref_name }}" | tr '/' '-')
          echo "SANITIZED_REF=$SANITIZED" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: kaiquedfelipe08/saasescola:${{ steps.sanitize.outputs.SANITIZED_REF }}
