name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup Docker Build
        uses: docker/setup-buildx-action@v3.10.0

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: kaiquedfelipe08/saasescola:${{ github.ref_name | replace('/', '-') }}
