# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: workflow CI

on:
  pull_request:
    branches: ['main']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.
      - name: start db
        run: DB_PASSWORD=${{ secrets.DB_PASSWORD }} DB_NAME=&{{ secrets.DB_NAME }} DATABASE_URL=${{ secrets.DATABASE_URL }}'docker compose up -d postgres

      - run: npm install

      - run: npm run eslint:fix
